ansible:
  hosts:
    vagrant_server:
      ansible_host: 192.168.33.10
  vars:
    ansible_connection: ssh
    ansible_ssh_user: vagrant
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    app_domain: 'devops-challenge.serasa.local'