---

- name: install key docker and nginx
  apt_key: url='{{ item }}'
  loop:
   - https://download.docker.com/linux/ubuntu/gpg
   - https://nginx.org/keys/nginx_signing.key

- name: adiciona repositorio nginx e docker
  apt_repository: repo='{{ item }}' update_cache=yes
  loop:
   - deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} edge 
   - deb http://nginx.org/packages/ubuntu {{ansible_distribution_release}} nginx
- name: cria diretorio ssl
  file:
    path: '{{ nginx_path_ssl }}'
    state: directory

- name: copia certificados
  copy:
    src: files/
    dest: '{{ nginx_path_ssl }}'

- name: instala docker-ce e nginx
  apt: name="{{ packages }}" state=latest
  vars:
    packages:
     - docker-ce
     - nginx

- name: pip install requirements
  pip: name="{{ item }}"
  loop:
    - docker
    - pyOpenSSL

- name: copia template nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - reload nginx

- name: adiciona usuario vagrant para o grupo docker
  user:
    name: vagrant
    groups: docker
    append: yes

- name: build image docker
  docker_image:
    name: '{{ docker_image_name }}'
    path: './{{ app_name }}'
    state: present
    tag: '{{ docker_image_tag }}'

- name: cria container application
  docker_container:
    name: '{{ docker_container_name }}'
    recreate: yes
    restart_policy: unless-stopped
    image: '{{ docker_image_name }}:{{ docker_image_tag }}'
    ports:
      - "8080:8080"

- name: Verifique se a página retorna um status 200 e falhe se a palavra Hey! You win não está no conteúdo da página
  uri:
    url: 'https://{{ app_domain }}'
    return_content: yes
    validate_certs: no
  register: this
  failed_when: "'Hey! You win' not in this.content"

