---

- name: cria diretorio ssl
  file:
    path: '{{ nginx_path_ssl }}'
    state: directory

- name: copia certificados
  copy:
    src: files/
    dest: '{{ nginx_path_ssl }}'

- name: habilita repositorio nginx
  template:
    src: nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo

- name: habilita repositorio docker
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo

- name: yum instala depedencias
  yum: name="{{ packages }}" state=latest
  vars:
    packages: '{{ yum_deps }}'

- name: pip instala depedencias
  pip: name="{{ item }}"
  loop:
    - docker
    - pyOpenSSL

- name: garantindo que docker e nginx habilitado e iniciado no boot
  service:
    name: '{{ item }}'
    state: started
    enabled: yes
  loop:
    - docker
    - nginx

- name: copia template nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - reload nginx

- name: adiciona usuario vagrant para o grupo docker
  user:
    name: vagrant
    groups: docker
    append: yes

- name: build image docker
  docker_image:
    name: '{{ docker_image_name }}'
    path: './{{ app_name }}'
    state: present
    tag: '{{ docker_image_tag }}'

- name: cria container application
  docker_container:
    name: '{{ docker_container_name }}'
    recreate: yes
    restart_policy: unless-stopped
    image: '{{ docker_image_name }}:{{ docker_image_tag }}'
    ports:
      - "8080:8080"

- name: desabilita selinux
  selinux:
    state: disabled
  notify: reboot server

- name: Verifique se a página retorna um status 200 e falhe se a palavra Hey! You win não está no conteúdo da página
  uri:
    url: 'https://{{ app_domain }}'
    return_content: yes
    validate_certs: no
  register: this
  failed_when: "'Hey! You win' not in this.content"


