---
- name: restart nginx
  systemd: name=nginx state=restarted

- name: validate nginx configuration
  command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: false

- name: reload nginx
  systemd: name=nginx state=reloaded

- name: reboot server
  reboot:
    msg: Reboot initiated by Ansible
    reboot_timeout: 110
    pre_reboot_delay: 2