---

- name: validate nginx configuration
  command: nginx -t -c /etc/nginx/nginx.conf
  listen: restart nginx
  changed_when: false

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
  listen: restart nginx

